'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
Imports System
Namespace AgendaView


	Partial Public Class [Default]

		''' <summary>
		''' form1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

		''' <summary>
		''' resourcesDataSource control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected resourcesDataSource As Global.System.Web.UI.WebControls.ObjectDataSource

		''' <summary>
		''' appointmentsDataSource control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected appointmentsDataSource As Global.System.Web.UI.WebControls.ObjectDataSource

		''' <summary>
		''' ASPxCallbackPanel1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxCallbackPanel1 As Global.DevExpress.Web.ASPxCallbackPanel

		''' <summary>
		''' ASPxScheduler1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxScheduler1 As Global.DevExpress.Web.ASPxScheduler.ASPxScheduler

		''' <summary>
		''' AgendaViewControl1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected AgendaViewControl1 As Global.AgendaView.AgendaViewControl
	End Class
End Namespace
