'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
Imports System
Namespace AgendaView


	Partial Public Class AgendaViewControl

		''' <summary>
		''' popupControl control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected popupControl As Global.DevExpress.Web.ASPxPopupControl

		''' <summary>
		''' ASPxFormLayout1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxFormLayout1 As Global.DevExpress.Web.ASPxFormLayout

		''' <summary>
		''' calendar control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected calendar As Global.DevExpress.Web.ASPxDateEdit

		''' <summary>
		''' btOK control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected btOK As Global.DevExpress.Web.ASPxButton

		''' <summary>
		''' btCancel control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected btCancel As Global.DevExpress.Web.ASPxButton

		''' <summary>
		''' ASPxSplitter1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxSplitter1 As Global.DevExpress.Web.ASPxSplitter

		''' <summary>
		''' GridControlResources control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected GridControlResources As Global.DevExpress.Web.ASPxCardView

		''' <summary>
		''' GridControlAppointments control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected GridControlAppointments As Global.DevExpress.Web.ASPxGridView
	End Class
End Namespace
